version: "3.9"
services:
  qr_market:
    build: .
    container_name: qr_market
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
